### ISSUE TITLE
Problem with mimetype

### ISSUE THREAD

**Issue by smir-ant** [beyer-stefan/gofiber-minifier#11]
I created a website on gofiber v2. html, css, js, images, pdf are used here... and every time the page loads, I get a lot of messages like:

```text
2024/11/22 11:00:41.001909 minifier.go:64: [Error] minifier does not exist for mime type
```

although I indicated that I only need to minify
```golang
app.Use(minifier.New(minifier.Config{
    MinifyHTML: true,
    MinifyCSS: true,
}))
```
how to fix it?

**Comment by smir-ant** [comment]
p.s. it works, but I'm not happy with the word error a lot.

**Comment by beyer-stefan** [comment]
I am really sorry for the confusion. This is how applications that I usually write look like:

```
	app = fiber.New(fiber.Config{ (...) })
	app.Use(recover.New(recover.Config{EnableStackTrace: true}))
	app.Use(compress.New(compress.Config{Level: compress.LevelBestCompression}))
	app.Use(etag.New(etag.Config{Weak: false}))

	app.Static("/", "./public")
```

So recoverer, compressions, and etag are ready + static files, 

After that I configure the minifier, e.g. like this:
```
	app.Use(minifier.New(minifier.Config{
		MinifyHTML: true,
		MinifyXML:  true,
		}))
	}
```
And after the minifier I would put all "normal" routes, application logic, etc.

It never occurred to me to to do it any other way, so I have never seen the error message your are seeing now.

The reason why I put the error message in my gofiber-minifier in the first place was to get a warning if I happened to place the minifier at the wrong position.

**Comment by beyer-stefan** [comment]
Bottom line:

I suggest that you change the order of your routes so you only minify content returned routes that return e. g. HTML or any other supported mime type.

Please let me know if that works for you.

I can remove the error message. However, that would still leave the problem of the minifier being called along with every request, which would be a bit of waste of CPU cycles.

**Comment by smir-ant** [comment]
yeap, it works, I appreciate the quick response and help. 
log is right way and don't remove it
but mb will be great to clarify this point in the readme

thank you

**Comment by smir-ant** [comment]
> After that I configure the minifier

stop..
need to minify before static mb?

cuz 
```golang
       app := fiber.New(fiber.Config{
		Prefork: true,
		Views: engine,
	})

	app.Static("/static", filepath.Join(execDir, "static"))
	
	app.Use(minifier.New(minifier.Config{
		MinifyHTML: true,
		MinifyCSS:  true,
	}))
```

will give me:
```css
@media (prefers-color-scheme: light) {
    :root {
        --color-back: #fff;
        --color-back_second: #f0f0f0;
        --color-front: #222222;
        --invert: invert(0);
    }
}

@media (prefers-color-scheme: dark) {
    :root {
        --color-back: #202020;
        --color-back_second: #383838;
        --color-front: #eee;
        --invert: invert(1);
    }
}

:root {
    --color-50proc: color-mix(in srgb, var(--color-front) 50%, transparent);
    --color-25proc: color-mix(in srgb, var(--color-front) 25%, transparent);
    --color-blue: #478cd5;
    --color-green: #7ac44d;
    --color-amber: #dd9672;
    /* --color-red: #e03a3c; */
    --color-red: #db4144;

    --borderRadius: 6px;
    --left-right-offset: 80px;

}
```

> [!IMPORTANT]  
> the minification didn't work => useless code?
<sub>(if you have a code for minifying files, and the files are not minified as a result, then what is the point of this code?)</sub>

but 
```golang
       app := fiber.New(fiber.Config{
		Prefork: true,
		Views: engine,
	})
	
	app.Use(minifier.New(minifier.Config{
		MinifyHTML: true,
		MinifyCSS:  true,
	}))

	app.Static("/static", filepath.Join(execDir, "static"))
```

will give
```css
@media(prefers-color-scheme:light){:root{--color-back:#fff;--color-back_second:#f0f0f0;--color-front:#222222;--invert:invert(0)}}@media(prefers-color-scheme:dark){:root{--color-back:#202020;--color-back_second:#383838;--color-front:#eee;--invert:invert(1)}}:root{--color-50proc:color-mix(in srgb, var(--color-front) 50%, transparent);--color-25proc:color-mix(in srgb, var(--color-front) 25%, transparent);--color-blue:#478cd5;--color-green:#7ac44d;--color-amber:#dd9672;--color-red:#db4144;--borderRadius:6px;--left-right-offset:80px}
```

(result is file in browser network tab)

> [!IMPORTANT]  
> but it will give me errors

👀
